<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\background.jpg" />
    <None Remove="Images\background.png" />
    <None Remove="Images\background_menu.png" />
    <None Remove="Images\Basic.png" />
    <None Remove="Images\bohater_dead.png" />
    <None Remove="Images\boss.gif" />
    <None Remove="Images\boss.png" />
    <None Remove="Images\boss_dead.png" />
    <None Remove="Images\czarodziej.png" />
    <None Remove="Images\heart.jpg" />
    <None Remove="Images\kostka.png" />
    <None Remove="Images\ludzik_dead.png" />
    <None Remove="Images\Mag.gif" />
    <None Remove="Images\Mage.png" />
    <None Remove="Images\nietoperz.png" />
    <None Remove="Images\nietoperz_dead.png" />
    <None Remove="Images\pajak.png" />
    <None Remove="Images\pająk_dead.png" />
    <None Remove="Images\pocisk_bohatera.png" />
    <None Remove="Images\pocisk_bossa.png" />
    <None Remove="Images\pocisk_bossa_triple.png" />
    <None Remove="Images\pocisk_nietoperza.png" />
    <None Remove="Images\pocisk_nietoperza_triple.png" />
    <None Remove="Images\pocisk_pająka.png" />
    <None Remove="Images\pocisk_pająka_triple.png" />
    <None Remove="Images\pocisk_wroga.png" />
    <None Remove="Images\pocisk_wroga_triple.png" />
    <None Remove="Images\Spider.png" />
    <None Remove="Images\Tank.png" />
    <None Remove="Images\tarcza.png" />
    <None Remove="Images\triple.png" />
    <None Remove="Images\triple_hero.png" />
    <None Remove="Video\boss.gif" />
    <None Remove="Video\czarodziej.gif" />
    <None Remove="Video\nietoperz.gif" />
    <None Remove="Video\pajak.gif" />
    <None Remove="Video\zamek.mp4" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\background.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\background_menu.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Basic.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\bohater_dead.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\boss.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\boss_dead.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\heart.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\kostka.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ludzik_dead.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Mag.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Mage.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\nietoperz_dead.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\pająk_dead.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\pocisk_bohatera.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\pocisk_bossa.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\pocisk_bossa_triple.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\pocisk_nietoperza.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\pocisk_nietoperza_triple.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\pocisk_pająka.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\pocisk_pająka_triple.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\pocisk_wroga.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\pocisk_wroga_triple.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Spider.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Tank.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\tarcza.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\triple_hero.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Content Include="Video\Hero.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Video\boss.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Video\czarodziej.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Video\nietoperz.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Video\pajak.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Video\zamek.mp4">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
  </ItemGroup>

</Project>
